apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:   
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ .Values.imageName }}:v{{ .Chart.AppVersion }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP   
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: http
            httpHeaders:
            - name: Custom-Header
              value: Awesome
