apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: martin.felin@helse-vest-ikt.no
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:  
    - http01:
        ingress:
          class: nginx