apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-world2
  name: hello-world2
  namespace: webapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world2
  type: ClusterIP
status:
  loadBalancer: {}
