apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 3
  template:
    metadata:
      labels:   
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ghcr.io/go4clouds/webapp:v0.1.0
        ports:
        - name: http
          containerPort: 80
          protocol: TCP   
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: http
            httpHeaders:
            - name: Custom-Header
              value: Awesome
